"""initial schema

Revision ID: 38d747d17de2
Revises: 5672d4b92134
Create Date: 2025-12-23 17:49:37.767785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d747d17de2'
down_revision: Union[str, Sequence[str], None] = '5672d4b92134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'is_expired')
    op.add_column('user_subscriptions', sa.Column('is_expired', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'is_expired')
    op.add_column('subscription_plans', sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
