"""initial schema

Revision ID: 4b7bc1890f61
Revises: 8f20bde0ebbd
Create Date: 2025-12-22 10:32:23.544483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7bc1890f61'
down_revision: Union[str, Sequence[str], None] = '8f20bde0ebbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_active_user_subscription'), table_name='user_subscriptions', postgresql_where='(is_active = true)')
    op.add_column('valuation_reports', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'valuation_reports', 'user_subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valuation_reports', type_='foreignkey')
    op.drop_column('valuation_reports', 'subscription_id')
    op.create_index(op.f('uq_active_user_subscription'), 'user_subscriptions', ['user_id'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
