"""initial schema

Revision ID: 5672d4b92134
Revises: fae72d4f7d58
Create Date: 2025-12-23 17:48:52.464166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5672d4b92134'
down_revision: Union[str, Sequence[str], None] = 'fae72d4f7d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_jobs')
    op.add_column('subscription_plans', sa.Column('is_expired', sa.Boolean(), nullable=True))
    op.alter_column('user_subscriptions', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'end_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('subscription_plans', 'is_expired')
    op.create_table('valuation_jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('valuation_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pdf_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], name=op.f('valuation_jobs_subscription_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('valuation_jobs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('valuation_jobs_pkey'))
    )
    # ### end Alembic commands ###
