"""initial schema

Revision ID: 6d298dc8100b
Revises: f1f8cdc125cc
Create Date: 2026-01-09 14:44:59.480004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d298dc8100b'
down_revision: Union[str, Sequence[str], None] = 'f1f8cdc125cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email_verified_at'), 'users', ['email_verified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verified_at'), table_name='users')
    # ### end Alembic commands ###
