"""initial schema

Revision ID: af67534dbd43
Revises: 38d747d17de2
Create Date: 2025-12-24 09:31:36.139604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af67534dbd43'
down_revision: Union[str, Sequence[str], None] = '38d747d17de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('razorpay_signature', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'payment_status')
    op.drop_column('user_subscriptions', 'razorpay_signature')
    op.drop_column('user_subscriptions', 'razorpay_payment_id')
    op.drop_column('user_subscriptions', 'razorpay_order_id')
    # ### end Alembic commands ###
