"""intial

Revision ID: c9490bf3ccb9
Revises: 28da05503d7a
Create Date: 2026-01-12 16:04:27.859912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9490bf3ccb9'
down_revision: Union[str, Sequence[str], None] = '28da05503d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_messages')
    op.drop_table('feedback')
    op.add_column('user_subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'cancelled_at')
    op.drop_column('user_subscriptions', 'auto_renew')
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('feedback_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('GENERAL', 'VALUATION', 'PAYMENT', 'SUBSCRIPTION', name='feedback_type'), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valuation_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='feedback_status'), autoincrement=False, nullable=True),
    sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedback_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('feedback_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender', postgresql.ENUM('USER', 'ADMIN', name='feedback_sender'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('feedback_messages_feedback_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_messages_pkey'))
    )
    # ### end Alembic commands ###
