"""initial schema

Revision ID: e282604cec73
Revises: 4b7bc1890f61
Create Date: 2025-12-22 10:37:50.265554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e282604cec73'
down_revision: Union[str, Sequence[str], None] = '4b7bc1890f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valuation_reports', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valuation_reports', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
