"""initial schema

Revision ID: f1f8cdc125cc
Revises: 3e066d69634e
Create Date: 2026-01-05 12:16:04.026636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f8cdc125cc'
down_revision: Union[str, Sequence[str], None] = '3e066d69634e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('currency_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'currency_code')
    # ### end Alembic commands ###
